//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace unreal_GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("unreal_GUI.Properties.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 一款简单的小工具，原开发目的是辅助用户将繁杂的命令操作转成简单的GUI操作，现正考虑将其打造成集合各种开发小工具的统一平台。 的本地化字符串。
        /// </summary>
        internal static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解压失败：{ex.Message} 的本地化字符串。
        /// </summary>
        internal static string exDecompression {
            get {
                return ResourceManager.GetString("exDecompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载失败：{ex.Message} 的本地化字符串。
        /// </summary>
        internal static string exDownload {
            get {
                return ResourceManager.GetString("exDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载失败，无法从服务器获取下载链接 的本地化字符串。
        /// </summary>
        internal static string exNoInternet {
            get {
                return ResourceManager.GetString("exNoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到目录：\n{path} 的本地化字符串。
        /// </summary>
        internal static string exPath {
            get {
                return ResourceManager.GetString("exPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取更新失败：{ex.Message} 的本地化字符串。
        /// </summary>
        internal static string exUpdate {
            get {
                return ResourceManager.GetString("exUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        internal static string msgAdd {
            get {
                return ResourceManager.GetString("msgAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加自定义按钮 的本地化字符串。
        /// </summary>
        internal static string msgAddCustomButtom {
            get {
                return ResourceManager.GetString("msgAddCustomButtom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string msgCancel {
            get {
                return ResourceManager.GetString("msgCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现新版本{latestVersion}\n\n更新内容:\n{updateBody}\n\n是否下载？ 的本地化字符串。
        /// </summary>
        internal static string msgCheckForUpdates {
            get {
                return ResourceManager.GetString("msgCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        internal static string msgClose {
            get {
                return ResourceManager.GetString("msgClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除自定义文件夹 的本地化字符串。
        /// </summary>
        internal static string msgDeleteCustomButtom {
            get {
                return ResourceManager.GetString("msgDeleteCustomButtom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已下载到：{downloadPath} 的本地化字符串。
        /// </summary>
        internal static string msgDownloadPath {
            get {
                return ResourceManager.GetString("msgDownloadPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string msgError {
            get {
                return ResourceManager.GetString("msgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        internal static string msgNo {
            get {
                return ResourceManager.GetString("msgNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string msgNotification {
            get {
                return ResourceManager.GetString("msgNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无更新内容 的本地化字符串。
        /// </summary>
        internal static string msgNoUpdateContent {
            get {
                return ResourceManager.GetString("msgNoUpdateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        internal static string msgOk {
            get {
                return ResourceManager.GetString("msgOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        internal static string msgSuccess {
            get {
                return ResourceManager.GetString("msgSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        internal static string msgWarning {
            get {
                return ResourceManager.GetString("msgWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        internal static string msgYes {
            get {
                return ResourceManager.GetString("msgYes", resourceCulture);
            }
        }
    }
}
